<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170312174914 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE stageNumber_has_costumes ADD CONSTRAINT FK_381A8CBCD80B7637 FOREIGN KEY (costumes_id) REFERENCES costumes (costumes_id)');
        $this->addSql('ALTER TABLE stageNumber_has_costumes ADD CONSTRAINT FK_381A8CBC9477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F17AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F17CD7D24A FOREIGN KEY (TV_id) REFERENCES TV (TV_id)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F19477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F15B94ADD2 FOREIGN KEY (radio_id) REFERENCES radio (radio_id)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F130A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F1C38F37CA FOREIGN KEY (disc_id) REFERENCES disc (disc_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F54567F5183 FOREIGN KEY (film_id) REFERENCES film (film_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F54B640FBA5 FOREIGN KEY (completeness_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F54DBE51D1B FOREIGN KEY (integration_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F547728D617 FOREIGN KEY (begin_thesaurus) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F5422915D1C FOREIGN KEY (ending_thesaurus) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F542534008B FOREIGN KEY (structure_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F541DFC29F2 FOREIGN KEY (performance_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F54AE679BDE FOREIGN KEY (spectators_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F54D4614D3A FOREIGN KEY (diegetic_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F54FA20049F FOREIGN KEY (musician_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number ADD CONSTRAINT FK_96901F547BD0F321 FOREIGN KEY (tempo_thesaurus) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_quotation ADD CONSTRAINT FK_3912D1BA1D232368 FOREIGN KEY (number_number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_quotation ADD CONSTRAINT FK_3912D1BAB4EA4E60 FOREIGN KEY (quotation_id) REFERENCES quotation (quotation_id)');
        $this->addSql('ALTER TABLE number_has_song ADD CONSTRAINT FK_EEA3C00130A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_song ADD CONSTRAINT FK_EEA3C001A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE number_has_completoptions ADD CONSTRAINT FK_ED5F987730A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_completoptions ADD CONSTRAINT FK_ED5F9877B976A76B FOREIGN KEY (completoptions_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stageNumber_has_number ADD CONSTRAINT FK_50D688130A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE stageNumber_has_number ADD CONSTRAINT FK_50D68819477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE number_has_exoticism ADD CONSTRAINT FK_D1FBFF161D232368 FOREIGN KEY (number_number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_exoticism ADD CONSTRAINT FK_D1FBFF16B659B97C FOREIGN KEY (exoticism_id) REFERENCES exoticism (exoticism_id)');
        $this->addSql('ALTER TABLE number_has_thesaurus ADD CONSTRAINT FK_56AA620F30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_thesaurus ADD CONSTRAINT FK_56AA620FCEDB68F4 FOREIGN KEY (integoptions_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_dancingtype ADD CONSTRAINT FK_9CC2B24630A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_dancingtype ADD CONSTRAINT FK_9CC2B246A4A7BAC2 FOREIGN KEY (dancingtype_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_dancesubgenre ADD CONSTRAINT FK_7242E09D30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_dancesubgenre ADD CONSTRAINT FK_7242E09D9C01BC05 FOREIGN KEY (dancesubgenre_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_dancecontent ADD CONSTRAINT FK_E14165F330A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_dancecontent ADD CONSTRAINT FK_E14165F3E333D4CF FOREIGN KEY (dancecontent_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_effects ADD CONSTRAINT FK_B1004AC30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_effects ADD CONSTRAINT FK_B1004AC568FBDB9 FOREIGN KEY (effects_id) REFERENCES effects (effects_id)');
        $this->addSql('ALTER TABLE number_has_musensemble ADD CONSTRAINT FK_8910748230A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_musensemble ADD CONSTRAINT FK_89107482C77C477B FOREIGN KEY (musensemble_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_costume ADD CONSTRAINT FK_78158BDD30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_costume ADD CONSTRAINT FK_78158BDDCFCDCFA6 FOREIGN KEY (costume_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_stereotype ADD CONSTRAINT FK_C7F1544F30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_stereotype ADD CONSTRAINT FK_C7F1544FBB26A68D FOREIGN KEY (stereotype_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_source ADD CONSTRAINT FK_2D5B131B30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_source ADD CONSTRAINT FK_2D5B131BABC76889 FOREIGN KEY (source_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_exoticismthesaurus ADD CONSTRAINT FK_6E78A2B830A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_exoticismthesaurus ADD CONSTRAINT FK_6E78A2B8B1FA28AC FOREIGN KEY (exoticism_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_dancemble ADD CONSTRAINT FK_F72B0BBD30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_dancemble ADD CONSTRAINT FK_F72B0BBD9577FDB6 FOREIGN KEY (dancemble_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_imaginary ADD CONSTRAINT FK_2951547C30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_imaginary ADD CONSTRAINT FK_2951547C88E9D8A6 FOREIGN KEY (imaginary_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_diegeticplace ADD CONSTRAINT FK_C82EFD6E30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_diegeticplace ADD CONSTRAINT FK_C82EFD6E8410650D FOREIGN KEY (diegetic_place_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_generallocalisation ADD CONSTRAINT FK_23D0AAE530A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_generallocalisation ADD CONSTRAINT FK_23D0AAE5BF30111 FOREIGN KEY (general_localisation_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_quotationthesaurus ADD CONSTRAINT FK_EC3BD90F30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_quotationthesaurus ADD CONSTRAINT FK_EC3BD90FB4EA4E60 FOREIGN KEY (quotation_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_generalmood ADD CONSTRAINT FK_A61CCF9530A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_generalmood ADD CONSTRAINT FK_A61CCF95C9A97E4A FOREIGN KEY (general_mood_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_musicalthesaurus ADD CONSTRAINT FK_F4921E6C30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_musicalthesaurus ADD CONSTRAINT FK_F4921E6C841FF228 FOREIGN KEY (musical_thesaurus_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_genre ADD CONSTRAINT FK_555BDE3E30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_genre ADD CONSTRAINT FK_555BDE3E4296D31F FOREIGN KEY (genre_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE number_has_choregraph ADD CONSTRAINT FK_42F4E26230A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_choregraph ADD CONSTRAINT FK_42F4E262217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE number_has_arranger ADD CONSTRAINT FK_39EC201330A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_arranger ADD CONSTRAINT FK_39EC2013217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE number_has_director ADD CONSTRAINT FK_F7B06DFD30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_director ADD CONSTRAINT FK_F7B06DFD217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE number_has_performer ADD CONSTRAINT FK_697957E830A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_performer ADD CONSTRAINT FK_697957E8217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE number_has_figurant ADD CONSTRAINT FK_845EAB3F30A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_figurant ADD CONSTRAINT FK_845EAB3F217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE number_has_editor ADD CONSTRAINT FK_BE209DD230A1DE10 FOREIGN KEY (number_id) REFERENCES number (number_id)');
        $this->addSql('ALTER TABLE number_has_editor ADD CONSTRAINT FK_BE209DD230766468 FOREIGN KEY (editors) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE person_has_quotation ADD CONSTRAINT FK_6E612C3B217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE person_has_quotation ADD CONSTRAINT FK_6E612C3BB4EA4E60 FOREIGN KEY (quotation_id) REFERENCES quotation (quotation_id)');
        $this->addSql('ALTER TABLE person_has_editor ADD CONSTRAINT FK_D6688534217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE person_has_editor ADD CONSTRAINT FK_D668853430766468 FOREIGN KEY (editors) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE song_has_radio ADD CONSTRAINT FK_63631E45A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_radio ADD CONSTRAINT FK_63631E455B94ADD2 FOREIGN KEY (radio_id) REFERENCES radio (radio_id)');
        $this->addSql('ALTER TABLE song_has_stageNumber ADD CONSTRAINT FK_8EB31DA3A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_stageNumber ADD CONSTRAINT FK_8EB31DA39477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE song_has_quotation ADD CONSTRAINT FK_296AF576A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_quotation ADD CONSTRAINT FK_296AF576B4EA4E60 FOREIGN KEY (quotation_id) REFERENCES quotation (quotation_id)');
        $this->addSql('ALTER TABLE song_has_disc ADD CONSTRAINT FK_F42FD827A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_disc ADD CONSTRAINT FK_F42FD827C38F37CA FOREIGN KEY (disc_id) REFERENCES disc (disc_id)');
        $this->addSql('ALTER TABLE song_has_songtype ADD CONSTRAINT FK_C50B10C3A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_songtype ADD CONSTRAINT FK_C50B10C33A047A9A FOREIGN KEY (songtype_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE song_has_lyricist ADD CONSTRAINT FK_3FCF5956A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_lyricist ADD CONSTRAINT FK_3FCF5956217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE song_has_composer ADD CONSTRAINT FK_D30D2E4FA0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_composer ADD CONSTRAINT FK_D30D2E4F7A8D2620 FOREIGN KEY (composer_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE song_has_TV ADD CONSTRAINT FK_1B136DE7A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_TV ADD CONSTRAINT FK_1B136DE77CD7D24A FOREIGN KEY (TV_id) REFERENCES TV (TV_id)');
        $this->addSql('ALTER TABLE song_has_editor ADD CONSTRAINT FK_5A7B7C31A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)');
        $this->addSql('ALTER TABLE song_has_editor ADD CONSTRAINT FK_5A7B7C3130766468 FOREIGN KEY (editors) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE stagenumber ADD CONSTRAINT FK_9BA3443AC54C8C93 FOREIGN KEY (type_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stagenumber ADD CONSTRAINT FK_9BA3443A7AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE stageNumber_has_costume ADD CONSTRAINT FK_9062B0C79477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE stageNumber_has_costume ADD CONSTRAINT FK_9062B0C7CFCDCFA6 FOREIGN KEY (costume_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stageNumber_has_musical ADD CONSTRAINT FK_DA14D4F9477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE stageNumber_has_musical ADD CONSTRAINT FK_DA14D4F839489F9 FOREIGN KEY (musical_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stageNumber_has_dancingstyle ADD CONSTRAINT FK_24C32FF49477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE stageNumber_has_dancingstyle ADD CONSTRAINT FK_24C32FF4A6C0EA20 FOREIGN KEY (dancingstyle_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stageNumber_has_musensemble ADD CONSTRAINT FK_50254C739477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE stageNumber_has_musensemble ADD CONSTRAINT FK_50254C73C77C477B FOREIGN KEY (musensemble_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stageNumber_has_genre ADD CONSTRAINT FK_E700089477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE stageNumber_has_genre ADD CONSTRAINT FK_E700084296D31F FOREIGN KEY (genre_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stagenumber_has_dancemble ADD CONSTRAINT FK_ECF1A03E9477DDBE FOREIGN KEY (stageNumber_id) REFERENCES stageNumber (stageNumber_id)');
        $this->addSql('ALTER TABLE stagenumber_has_dancemble ADD CONSTRAINT FK_ECF1A03E9577FDB6 FOREIGN KEY (dancemble_id) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE stageshow_has_composer ADD CONSTRAINT FK_10F12A037AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE stageshow_has_composer ADD CONSTRAINT FK_10F12A03217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE stageshow_has_book ADD CONSTRAINT FK_B58807737AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE stageshow_has_book ADD CONSTRAINT FK_B5880773217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE stageshow_has_lyricist ADD CONSTRAINT FK_FC335D1A7AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE stageshow_has_lyricist ADD CONSTRAINT FK_FC335D1A217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE stageshow_has_choreographer ADD CONSTRAINT FK_9E451D8A7AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE stageshow_has_choreographer ADD CONSTRAINT FK_9E451D8A217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE stageshow_has_director ADD CONSTRAINT FK_9612FF2B7AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE stageshow_has_director ADD CONSTRAINT FK_9612FF2B217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE stageshow_has_design ADD CONSTRAINT FK_DEBB6E2B7AC68360 FOREIGN KEY (stageShow_id) REFERENCES stageShow (stageShow_id)');
        $this->addSql('ALTER TABLE stageshow_has_design ADD CONSTRAINT FK_DEBB6E2B217BBB47 FOREIGN KEY (person_id) REFERENCES person (person_id)');
        $this->addSql('ALTER TABLE validation ADD CONSTRAINT FK_16AC5B6EA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE link DROP FOREIGN KEY FK_36AC99F17AC68360');
        $this->addSql('ALTER TABLE link DROP FOREIGN KEY FK_36AC99F17CD7D24A');
        $this->addSql('ALTER TABLE link DROP FOREIGN KEY FK_36AC99F19477DDBE');
        $this->addSql('ALTER TABLE link DROP FOREIGN KEY FK_36AC99F15B94ADD2');
        $this->addSql('ALTER TABLE link DROP FOREIGN KEY FK_36AC99F130A1DE10');
        $this->addSql('ALTER TABLE link DROP FOREIGN KEY FK_36AC99F1C38F37CA');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F54567F5183');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F54B640FBA5');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F54DBE51D1B');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F547728D617');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F5422915D1C');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F542534008B');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F541DFC29F2');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F54AE679BDE');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F54D4614D3A');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F54FA20049F');
        $this->addSql('ALTER TABLE number DROP FOREIGN KEY FK_96901F547BD0F321');
        $this->addSql('ALTER TABLE number_has_arranger DROP FOREIGN KEY FK_39EC201330A1DE10');
        $this->addSql('ALTER TABLE number_has_arranger DROP FOREIGN KEY FK_39EC2013217BBB47');
        $this->addSql('ALTER TABLE number_has_choregraph DROP FOREIGN KEY FK_42F4E26230A1DE10');
        $this->addSql('ALTER TABLE number_has_choregraph DROP FOREIGN KEY FK_42F4E262217BBB47');
        $this->addSql('ALTER TABLE number_has_completoptions DROP FOREIGN KEY FK_ED5F987730A1DE10');
        $this->addSql('ALTER TABLE number_has_completoptions DROP FOREIGN KEY FK_ED5F9877B976A76B');
        $this->addSql('ALTER TABLE number_has_costume DROP FOREIGN KEY FK_78158BDD30A1DE10');
        $this->addSql('ALTER TABLE number_has_costume DROP FOREIGN KEY FK_78158BDDCFCDCFA6');
        $this->addSql('ALTER TABLE number_has_dancecontent DROP FOREIGN KEY FK_E14165F330A1DE10');
        $this->addSql('ALTER TABLE number_has_dancecontent DROP FOREIGN KEY FK_E14165F3E333D4CF');
        $this->addSql('ALTER TABLE number_has_dancemble DROP FOREIGN KEY FK_F72B0BBD30A1DE10');
        $this->addSql('ALTER TABLE number_has_dancemble DROP FOREIGN KEY FK_F72B0BBD9577FDB6');
        $this->addSql('ALTER TABLE number_has_dancesubgenre DROP FOREIGN KEY FK_7242E09D30A1DE10');
        $this->addSql('ALTER TABLE number_has_dancesubgenre DROP FOREIGN KEY FK_7242E09D9C01BC05');
        $this->addSql('ALTER TABLE number_has_dancingtype DROP FOREIGN KEY FK_9CC2B24630A1DE10');
        $this->addSql('ALTER TABLE number_has_dancingtype DROP FOREIGN KEY FK_9CC2B246A4A7BAC2');
        $this->addSql('ALTER TABLE number_has_diegeticplace DROP FOREIGN KEY FK_C82EFD6E30A1DE10');
        $this->addSql('ALTER TABLE number_has_diegeticplace DROP FOREIGN KEY FK_C82EFD6E8410650D');
        $this->addSql('ALTER TABLE number_has_director DROP FOREIGN KEY FK_F7B06DFD30A1DE10');
        $this->addSql('ALTER TABLE number_has_director DROP FOREIGN KEY FK_F7B06DFD217BBB47');
        $this->addSql('ALTER TABLE number_has_editor DROP FOREIGN KEY FK_BE209DD230A1DE10');
        $this->addSql('ALTER TABLE number_has_editor DROP FOREIGN KEY FK_BE209DD230766468');
        $this->addSql('ALTER TABLE number_has_effects DROP FOREIGN KEY FK_B1004AC30A1DE10');
        $this->addSql('ALTER TABLE number_has_effects DROP FOREIGN KEY FK_B1004AC568FBDB9');
        $this->addSql('ALTER TABLE number_has_exoticism DROP FOREIGN KEY FK_D1FBFF161D232368');
        $this->addSql('ALTER TABLE number_has_exoticism DROP FOREIGN KEY FK_D1FBFF16B659B97C');
        $this->addSql('ALTER TABLE number_has_exoticismthesaurus DROP FOREIGN KEY FK_6E78A2B830A1DE10');
        $this->addSql('ALTER TABLE number_has_exoticismthesaurus DROP FOREIGN KEY FK_6E78A2B8B1FA28AC');
        $this->addSql('ALTER TABLE number_has_figurant DROP FOREIGN KEY FK_845EAB3F30A1DE10');
        $this->addSql('ALTER TABLE number_has_figurant DROP FOREIGN KEY FK_845EAB3F217BBB47');
        $this->addSql('ALTER TABLE number_has_generallocalisation DROP FOREIGN KEY FK_23D0AAE530A1DE10');
        $this->addSql('ALTER TABLE number_has_generallocalisation DROP FOREIGN KEY FK_23D0AAE5BF30111');
        $this->addSql('ALTER TABLE number_has_generalmood DROP FOREIGN KEY FK_A61CCF9530A1DE10');
        $this->addSql('ALTER TABLE number_has_generalmood DROP FOREIGN KEY FK_A61CCF95C9A97E4A');
        $this->addSql('ALTER TABLE number_has_genre DROP FOREIGN KEY FK_555BDE3E30A1DE10');
        $this->addSql('ALTER TABLE number_has_genre DROP FOREIGN KEY FK_555BDE3E4296D31F');
        $this->addSql('ALTER TABLE number_has_imaginary DROP FOREIGN KEY FK_2951547C30A1DE10');
        $this->addSql('ALTER TABLE number_has_imaginary DROP FOREIGN KEY FK_2951547C88E9D8A6');
        $this->addSql('ALTER TABLE number_has_musensemble DROP FOREIGN KEY FK_8910748230A1DE10');
        $this->addSql('ALTER TABLE number_has_musensemble DROP FOREIGN KEY FK_89107482C77C477B');
        $this->addSql('ALTER TABLE number_has_musicalthesaurus DROP FOREIGN KEY FK_F4921E6C30A1DE10');
        $this->addSql('ALTER TABLE number_has_musicalthesaurus DROP FOREIGN KEY FK_F4921E6C841FF228');
        $this->addSql('ALTER TABLE number_has_performer DROP FOREIGN KEY FK_697957E830A1DE10');
        $this->addSql('ALTER TABLE number_has_performer DROP FOREIGN KEY FK_697957E8217BBB47');
        $this->addSql('ALTER TABLE number_has_quotation DROP FOREIGN KEY FK_3912D1BA1D232368');
        $this->addSql('ALTER TABLE number_has_quotation DROP FOREIGN KEY FK_3912D1BAB4EA4E60');
        $this->addSql('ALTER TABLE number_has_quotationthesaurus DROP FOREIGN KEY FK_EC3BD90F30A1DE10');
        $this->addSql('ALTER TABLE number_has_quotationthesaurus DROP FOREIGN KEY FK_EC3BD90FB4EA4E60');
        $this->addSql('ALTER TABLE number_has_song DROP FOREIGN KEY FK_EEA3C00130A1DE10');
        $this->addSql('ALTER TABLE number_has_song DROP FOREIGN KEY FK_EEA3C001A0BDB2F3');
        $this->addSql('ALTER TABLE number_has_source DROP FOREIGN KEY FK_2D5B131B30A1DE10');
        $this->addSql('ALTER TABLE number_has_source DROP FOREIGN KEY FK_2D5B131BABC76889');
        $this->addSql('ALTER TABLE number_has_stereotype DROP FOREIGN KEY FK_C7F1544F30A1DE10');
        $this->addSql('ALTER TABLE number_has_stereotype DROP FOREIGN KEY FK_C7F1544FBB26A68D');
        $this->addSql('ALTER TABLE number_has_thesaurus DROP FOREIGN KEY FK_56AA620F30A1DE10');
        $this->addSql('ALTER TABLE number_has_thesaurus DROP FOREIGN KEY FK_56AA620FCEDB68F4');
        $this->addSql('ALTER TABLE person_has_editor DROP FOREIGN KEY FK_D6688534217BBB47');
        $this->addSql('ALTER TABLE person_has_editor DROP FOREIGN KEY FK_D668853430766468');
        $this->addSql('ALTER TABLE person_has_quotation DROP FOREIGN KEY FK_6E612C3B217BBB47');
        $this->addSql('ALTER TABLE person_has_quotation DROP FOREIGN KEY FK_6E612C3BB4EA4E60');
        $this->addSql('ALTER TABLE song_has_tv DROP FOREIGN KEY FK_1B136DE7A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_tv DROP FOREIGN KEY FK_1B136DE77CD7D24A');
        $this->addSql('ALTER TABLE song_has_composer DROP FOREIGN KEY FK_D30D2E4FA0BDB2F3');
        $this->addSql('ALTER TABLE song_has_composer DROP FOREIGN KEY FK_D30D2E4F7A8D2620');
        $this->addSql('ALTER TABLE song_has_disc DROP FOREIGN KEY FK_F42FD827A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_disc DROP FOREIGN KEY FK_F42FD827C38F37CA');
        $this->addSql('ALTER TABLE song_has_editor DROP FOREIGN KEY FK_5A7B7C31A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_editor DROP FOREIGN KEY FK_5A7B7C3130766468');
        $this->addSql('ALTER TABLE song_has_lyricist DROP FOREIGN KEY FK_3FCF5956A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_lyricist DROP FOREIGN KEY FK_3FCF5956217BBB47');
        $this->addSql('ALTER TABLE song_has_quotation DROP FOREIGN KEY FK_296AF576A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_quotation DROP FOREIGN KEY FK_296AF576B4EA4E60');
        $this->addSql('ALTER TABLE song_has_radio DROP FOREIGN KEY FK_63631E45A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_radio DROP FOREIGN KEY FK_63631E455B94ADD2');
        $this->addSql('ALTER TABLE song_has_songtype DROP FOREIGN KEY FK_C50B10C3A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_songtype DROP FOREIGN KEY FK_C50B10C33A047A9A');
        $this->addSql('ALTER TABLE song_has_stagenumber DROP FOREIGN KEY FK_8EB31DA3A0BDB2F3');
        $this->addSql('ALTER TABLE song_has_stagenumber DROP FOREIGN KEY FK_8EB31DA39477DDBE');
        $this->addSql('ALTER TABLE stageNumber_has_costume DROP FOREIGN KEY FK_9062B0C79477DDBE');
        $this->addSql('ALTER TABLE stageNumber_has_costume DROP FOREIGN KEY FK_9062B0C7CFCDCFA6');
        $this->addSql('ALTER TABLE stagenumber_has_costumes DROP FOREIGN KEY FK_381A8CBCD80B7637');
        $this->addSql('ALTER TABLE stagenumber_has_costumes DROP FOREIGN KEY FK_381A8CBC9477DDBE');
        $this->addSql('ALTER TABLE stageNumber_has_dancingstyle DROP FOREIGN KEY FK_24C32FF49477DDBE');
        $this->addSql('ALTER TABLE stageNumber_has_dancingstyle DROP FOREIGN KEY FK_24C32FF4A6C0EA20');
        $this->addSql('ALTER TABLE stageNumber_has_genre DROP FOREIGN KEY FK_E700089477DDBE');
        $this->addSql('ALTER TABLE stageNumber_has_genre DROP FOREIGN KEY FK_E700084296D31F');
        $this->addSql('ALTER TABLE stageNumber_has_musensemble DROP FOREIGN KEY FK_50254C739477DDBE');
        $this->addSql('ALTER TABLE stageNumber_has_musensemble DROP FOREIGN KEY FK_50254C73C77C477B');
        $this->addSql('ALTER TABLE stageNumber_has_musical DROP FOREIGN KEY FK_DA14D4F9477DDBE');
        $this->addSql('ALTER TABLE stageNumber_has_musical DROP FOREIGN KEY FK_DA14D4F839489F9');
        $this->addSql('ALTER TABLE stagenumber_has_number DROP FOREIGN KEY FK_50D688130A1DE10');
        $this->addSql('ALTER TABLE stagenumber_has_number DROP FOREIGN KEY FK_50D68819477DDBE');
        $this->addSql('ALTER TABLE stageNumber DROP FOREIGN KEY FK_9BA3443AC54C8C93');
        $this->addSql('ALTER TABLE stageNumber DROP FOREIGN KEY FK_9BA3443A7AC68360');
        $this->addSql('ALTER TABLE stagenumber_has_dancemble DROP FOREIGN KEY FK_ECF1A03E9477DDBE');
        $this->addSql('ALTER TABLE stagenumber_has_dancemble DROP FOREIGN KEY FK_ECF1A03E9577FDB6');
        $this->addSql('ALTER TABLE stageshow_has_book DROP FOREIGN KEY FK_B58807737AC68360');
        $this->addSql('ALTER TABLE stageshow_has_book DROP FOREIGN KEY FK_B5880773217BBB47');
        $this->addSql('ALTER TABLE stageshow_has_choreographer DROP FOREIGN KEY FK_9E451D8A7AC68360');
        $this->addSql('ALTER TABLE stageshow_has_choreographer DROP FOREIGN KEY FK_9E451D8A217BBB47');
        $this->addSql('ALTER TABLE stageshow_has_composer DROP FOREIGN KEY FK_10F12A037AC68360');
        $this->addSql('ALTER TABLE stageshow_has_composer DROP FOREIGN KEY FK_10F12A03217BBB47');
        $this->addSql('ALTER TABLE stageshow_has_design DROP FOREIGN KEY FK_DEBB6E2B7AC68360');
        $this->addSql('ALTER TABLE stageshow_has_design DROP FOREIGN KEY FK_DEBB6E2B217BBB47');
        $this->addSql('ALTER TABLE stageshow_has_director DROP FOREIGN KEY FK_9612FF2B7AC68360');
        $this->addSql('ALTER TABLE stageshow_has_director DROP FOREIGN KEY FK_9612FF2B217BBB47');
        $this->addSql('ALTER TABLE stageshow_has_lyricist DROP FOREIGN KEY FK_FC335D1A7AC68360');
        $this->addSql('ALTER TABLE stageshow_has_lyricist DROP FOREIGN KEY FK_FC335D1A217BBB47');
        $this->addSql('ALTER TABLE validation DROP FOREIGN KEY FK_16AC5B6EA76ED395');
    }
}
